### ISSUE TITLE
Unable to load the trained model

### ISSUE THREAD

**Issue by thak123** [shoarora/lmtuners#14]
Thanks for your contribution and previous bug fixes.
I was able to train an Albert model from scratch.

But I am facing issues with using PyTorch-Lightning saved .ckpt file in HuggingFace code-base that I have.
I cannot use the .ckpt file directly, cause there is no corresponding index file present.(frompretrained
method throws error)
I am not entirely sure why pytorch-Lightning is saving model in ckpt format which is tf convention than the usual pytorch pt or bin

**Comment by shoarora** [comment]
The `ckpt` files produced by lightning save optimizer and training state data as well ([their docs](https://pytorch-lightning.readthedocs.io/en/latest/weights_loading.html))

It's not directly compatible with `.from_pretrained`.  You need to explicitly save the underlying transformer with `.save_pretrained()`.  The train script does this at the [very end](https://github.com/shoarora/lmtuners/blob/master/experiments/disc_lm_small/train_electra_small.py#L101).

you can load your checkpoint with lightning and then call the huggingface `.save_pretrained` to get the huggingface compatible weights

**Comment by thak123** [comment]
Yes. Thanks for pointing out that.

I forgot to check the folder named final. The pre-trained models in PyTorch format are present there.
